### ISSUE TITLE
#1 BioCard

### ISSUE THREAD

**Issue by manukao** [manukao/interactive-portfolio-project-1#1]
### User Story:

As a user of the portfolio website, 
I want to view the developer's bio 
to get a brief introduction about the person behind the app.

Acceptance Criteria:

- [x] Display an avatar of the developer
- [x] Display the developers name
- [x] Display a short info text about the developer
- [x] Display at least three info tags about the developers background

Tasks:

- [x] Create a developer object that includes avatar, name, infoText and infoTags
- [x] Create a BioCard component to render the developers properties
- [x] Import and display the avatar asset
- [x] Display the name and infoText
- [x] Display the infoTags
- [x] All acceptance criteria are covered by component testing

![Image](https://user-images.githubusercontent.com/97320894/229383116-d466c4d3-a776-4a46-831b-77b78598bc9f.png)

**Comment by rabe200** [comment]
lgtm
