### ISSUE TITLE
#8 TestimonialsCard

### ISSUE THREAD

**Issue by manukao** [manukao/interactive-portfolio-project-1#15]
User Story:
As a user of the portfolio website,
I want to see some testimonials regarding the developer or their work
as it proves some credibility

Acceptance Criteria:

- [x] Display a collection of testimonials

Tasks:

- [x] Add a testimonials array to the developer object
- [x] Create a TestimonialsCard component to render the testimonials, e.g. as a marquee
- [ ] (Display an avatar/logo for the commenting person)
- [x] Display a short testimonial text
- [x] Display the name or company of the commenting person
- [x] All acceptance criteria are covered by component testing

![Image](https://user-images.githubusercontent.com/97320894/231124535-712c3bb4-a572-4807-bc90-f6189af1f77a.png)

**Comment by rabe200** [comment]
lgtm
