### ISSUE TITLE
#10 UI/UX

### ISSUE THREAD

**Issue by manukao** [manukao/interactive-portfolio-project-1#17]
User Story:

As a user of the portfolio website, 
I want to have a polished user interface and user experience 
so that I can easily enjoy navigating and learning about the developer and their projects

Acceptance Criteria:

- [ ] Implement a new UI design that enhances the website's visual appeal and improves the user experience
- [ ] Ensure that the new design is consistent across all pages and components

Tasks:

- [ ] Design new UI elements / update existing ones to fit the new design
- [ ] Incorporate interactive elements such as animations, hover effects, and modals to engage the user
- [x] Incorporate a 3D Panorama background that is interactive

![Image](https://user-images.githubusercontent.com/97320894/231772965-4eb223f7-7abf-4e2c-a847-edd131608c4e.png)

**Comment by AnjaSiewert** [comment]
LGTM 🚀
