### ISSUE TITLE
#2 LocationCard

### ISSUE THREAD

**Issue by manukao** [manukao/interactive-portfolio-project-1#2]
### User Story:

As a user of the portfolio website, 
I want to learn about the developer's location
as it may be relevant if I intend to work with them.

Acceptance Criteria:

- [x] Display a Map of the developers area
- [x] Display a marker of the developers location
- [x] Display the local weather
- [x] Display the local time

Tasks:

- [x] Add the location property to the developer object that includes: city, lng, lat, and timezone
- [x] Create a LocationCard component to render a map, time and weather infos
- [x] Fetch a maps APIs data for the developers city
- [x] Set a marker that points to the developers lng and lat
- [x] Create a WeatherBadge component to render the local weather
- [x] Fetch a weather APIs data using SWR and set a five minute interval
- [x] (Bonus: Define a function for the local time and render it)
- [x] use a .env file to store the API Keys and store/manage them with Vercel
- [x] All acceptance criteria are covered by component testing

![Image](https://user-images.githubusercontent.com/97320894/229384678-dbdd47a0-7a53-4e86-8b10-c0788ddd6f0c.png)

**Comment by rabe200** [comment]
lgtm
